from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"

FACE_DIR = DATA_DIR / "face"
FINGERPRINT_DIR = DATA_DIR / "fingerprint"
FINGERPRINT_RAW_DIR = FINGERPRINT_DIR / "raw"
FINGERPRINT_PROCESSED_DIR = FINGERPRINT_DIR / "processed"

FACE_DIR.mkdir(parents=True, exist_ok=True)
FINGERPRINT_DIR.mkdir(parents=True, exist_ok=True)
FINGERPRINT_RAW_DIR.mkdir(parents=True, exist_ok=True)
FINGERPRINT_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

FACE_MODEL_NAME = "Facenet512"
FACE_DETECTOR_BACKEND = "opencv"
FACE_DISTANCE_THRESHOLD = 0.35

FINGERPRINT_MIN_BRIGHTNESS = 20
FINGERPRINT_MAX_BRIGHTNESS = 245
FINGERPRINT_MIN_SHARPNESS = 10.0
FINGERPRINT_MIN_FOREGROUND_RATIO = 0.08

FINGERPRINT_MIN_MATCH_SCORE = 0.45
FINGERPRINT_MIN_ORB_MATCHES = 10